version: 2
updates:
  - package-ecosystem: npm
    directory: "/hatebu"
    schedule:
      interval: "monthly"
      time: "19:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "masutaka"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/github"
    schedule:
      interval: "monthly"
      time: "19:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "masutaka"
    open-pull-requests-limit: 10
