version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/github"
    update_schedule: "monthly"
    allowed_updates:
      - match:
          update_type: "all"
    automerged_updates:
      - match:
          update_type: "semver:patch"
  - package_manager: "javascript"
    directory: "/hatebu"
    update_schedule: "monthly"
    allowed_updates:
      - match:
          update_type: "all"
    automerged_updates:
      - match:
          update_type: "semver:patch"
