name: Pushover

on:
  workflow_call:

jobs:
  pushover:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: pushover-actions
      uses: umahmood/pushover-actions@v1.1.0
      env:
        PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_API_KEY }}
        PUSHOVER_USER: ${{ secrets.PUSHOVER_USER_KEY }}
      with:
        status: "failure"
        title: "Failed ${{ github.repository }}'s workflow (${{ github.workflow }})"
        url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        priority: 1 # High
